server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  application:
    name: SFC
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://121.196.205.160:3306/store?characterEncoding=UTF-8&useUnicode=true&serverTimezone=UTC&autoReconnect=true
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
      initial-size: 5
      max-active: 20
      min-idle: 20
      max-wait: 10000
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
  redis:
      host: localhost
      port: 6379
      pool.max-idle: 8
      pool.min-idle: 0
      pool.max-active: 8
      pool.max-wait: -1
  mvc:
    view:
      prefix:
mybatis:
    mapper-locations: classpath:Mapper/*.xml
logging:
  level:
    com.helper.store: debug
